# Generated by Django 6.1.1 on 2026-10-05 16:57

import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_appointment_doctorschedule'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', hospital.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
